# Generated by Django 5.1.4 on 2024-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=124),
        ),
    ]
