# Generated by Django 5.1.4 on 2024-12-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='reserved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
