# Generated by Django 5.1.4 on 2024-12-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='minimum_age',
            field=models.IntegerField(default=0),
        ),
    ]
